import React from 'react';
import { Sparkles, BrainCircuit } from 'lucide-react';

export default function ExplanationBox({ result }) {
  if (!result) return null;

  return (
    <div className="glass rounded-xl p-8 w-full max-w-2xl mx-auto border border-white/10 shadow-2xl mt-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <div className="flex items-center gap-3 mb-6 border-b border-white/10 pb-4">
        <div className="p-2 bg-primary/20 rounded-lg text-primary">
          <BrainCircuit size={24} />
        </div>
        <div>
          <h2 className="text-xl font-bold text-foreground flex items-center gap-2">
            GenAI Explanation
            <Sparkles className="text-primary h-4 w-4" />
          </h2>
          <p className="text-xs text-muted-foreground">Generated by AI analysis model</p>
        </div>
      </div>

      <div className="prose prose-invert max-w-none">
        <p className="text-foreground/90 leading-relaxed text-lg font-light">
          {result.explanation}
        </p>
      </div>

      <div className="mt-8">
        <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-4">Key Factors</h3>
        <div className="flex flex-wrap gap-2">
          {result.key_factors.map((factor, index) => (
            <span 
              key={index}
              className="inline-flex items-center rounded-full border border-white/10 bg-background/50 px-3 py-1 text-sm font-medium text-foreground backdrop-blur-sm shadow-sm"
            >
              {factor}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}
